### ISSUE TITLE
是否可以考虑将pinyin.txt直接embed到编译出的binary executable里

### ISSUE THREAD

**Issue by XD-DENG** [chain-zhang/pinyin#3]
现在你的实现是每次init()的时候都会到github下载pinyin.txt，https://github.com/chain-zhang/pinyin/blob/68f4679e62c8573e645309aae8731bd53922ea00/pinyin.go#L82

但这样会有若干弊端：
- 每次init()都需要再一次下载这个txt文件
- 如果在下载这个package之后，by right，用户应该可以在没有网络的情况下继续使用这个package。但因为需要下载这个txt文件，用户必须在有网络的情况下才能使用。

是否可以考虑将这个txt文件直接embed到最终编译出的binary executable里？这样我上面提到的两个问题就都能得到解决了。可以考虑使用这些package：https://github.com/avelino/awesome-go#resource-embedding

拙见，供你参考

**Comment by XD-DENG** [comment]
或者可以考虑将整个txt文件的内容作为一个“变量”存放到一个`.go`文件中。这样上面提到的问题也能够得到解决，因为去除了package安装成功之后对网络connectivity的依赖；Performance相信也并不会比现在的实现差。

**Comment by shunway** [comment]
已创建分支解决：[shunway/pinyin](//github.com/shunway/pinyin)

**Comment by XD-DENG** [comment]
@shunway 可以考虑raise 一个pull request贡献回upstream？

**Comment by chain-zhang** [comment]
@XD-DENG 感谢提意见，有时间我更新一下。

**Comment by chain-zhang** [comment]
> 考虑将整个txt文件的内容作为一个“变量”存放到一个.go文件中

@XD-DENG 已经修改过来了

**Comment by XD-DENG** [comment]
@chain-zhang  👍
